Description of current
Home > src > mconf > current.m
current
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
current
This function is called by:
current
currentWire
SUBFUNCTIONS
function obj = current(x,y,c,varargin)
function set.x(obj,x)
function set.y(obj,y)
function set.c(obj,c)
function set.curr(obj,c)
function curr = get.curr(obj)
SOURCE CODE
classdef current < handle & matlab.mixin.Heterogeneous
    properties(GetAccess=public,SetAccess=public)
        x = 0;
        y = 0;
        Parent = [];
        Children = [];
    end
    properties(Dependent)
        curr
    end
    properties(Access=private)
        c = 1;
    end
    methods
        function obj = current(x,y,c,varargin)
            narginchk(3,4);
            obj.x = x;
            obj.y = y;
            obj.c = c;
            if nargin==4
                relCur = varargin{1};
                assert(~isempty(relCur) && isa(relCur,'current'));
                obj.Parent = relCur;
                if isempty(obj.Children)
                    obj.Parent.Children = obj;
                else
                    obj.Parent.Children(end+1) = obj;
                end
            end
        end
        function set.x(obj,x)
            obj.x = x;
        end
        function set.y(obj,y)
            obj.y = y;
        end
        function set.c(obj,c)
            obj.c = c;
        end
        function set.curr(obj,c)
            obj.c = c;
            if ~isempty(obj.Parent)
                obj.c = obj.c * obj.Parent.c;
            end
        end
        function curr = get.curr(obj)
            curr = obj.c;
            if ~isempty(obj.Parent)
                curr = curr * obj.Parent.c;
            end
        end
    end
    methods (Abstract)
        bx = magFieldX(obj,x,y);
        by = magFieldY(obj,x,y);
    end
end